# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
import os
import random

class TestTest1():
  def setup_method(self, method):
        chrome_options = Options()

        # Tạo thư mục profile riêng cho Selenium
        custom_profile = r"D:\selenium_profile"
        os.makedirs(custom_profile, exist_ok=True)

        chrome_options.add_argument(f"--user-data-dir={custom_profile}")
        chrome_options.add_argument("--profile-directory=Profile 1")  # có thể đặt tên khác

        # Tùy chọn: tránh cảnh báo automation
        chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"])
        chrome_options.add_experimental_option("useAutomationExtension", False)

        # Tùy chọn: không đóng trình duyệt ngay khi chạy xong
        chrome_options.add_experimental_option("detach", True)
        # chrome_options.add_argument("--incognito")
        # Mở trình duyệt
        self.driver = webdriver.Chrome(options=chrome_options)
        self.driver.maximize_window()
        self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    # Test name: test_1
    # Step # | name | target | value
    # 1 | open | /forms/d/e/1FAIpQLScfnbNpqD8HBYFvae7ImE-yTxvJnGsefKG5VXTsVkGpUYvM1A/viewform | 
    
    # 2 | setWindowSize | 1061x816 | 
    # self.driver.set_window_size(1061, 816)
    # time.sleep(2)
    # 3 | click | css=.kCyAyd .NPEfkd | 
    # self.driver.find_element(By.CSS_SELECTOR, ".kCyAyd .NPEfkd").click()
    # time.sleep(2)
    # 4 | click | css=.qs41qe .NPEfkd | 
    # self.driver.find_element(By.CSS_SELECTOR, ".uArJ5e.UQuaGc.kCyAyd.ARrCac").click()
    # time.sleep(2)
    # button = self.driver.find_element(By.CSS_SELECTOR, ".uArJ5e.UQuaGc.kCyAyd.ARrCac")
    # self.driver.execute_script("arguments[0].click();", button)
    # 5 | click | css=.YhQJj > .l4V7wb | 
    # self.driver.get("https://docs.google.com/forms/d/e/1FAIpQLScfnbNpqD8HBYFvae7ImE-yTxvJnGsefKG5VXTsVkGpUYvM1A/viewform")
    # time.sleep(2)
    
    
    # 6 | click | css=.whsOnd | 
    # self.driver.find_element(By.CSS_SELECTOR, ".whsOnd").click()
    time.sleep(2)
    # 7 | type | css=.whsOnd | vaquan0508@gmail.com
    with open("email.txt", "r", encoding="utf-8") as f:
      emails = [line.strip() for line in f.readlines() if line.strip()]
    # print(email for email in emails)
    for email in emails:
      # self.setup_method()
      self.driver.get("https://docs.google.com/forms/d/e/1FAIpQLScfnbNpqD8HBYFvae7ImE-yTxvJnGsefKG5VXTsVkGpUYvM1A/viewform")
      time.sleep(2)
      self.driver.find_element(By.CSS_SELECTOR, ".YhQJj > .l4V7wb").click()
      time.sleep(2)
      # self.driver.find_element(By.CSS_SELECTOR, ".YhQJj > .l4V7wb").click()
      # time.sleep(2)
      input = self.driver.find_element(By.CSS_SELECTOR, ".whsOnd.zHQkBf")
      input.clear()
      input.send_keys(email)
      self.driver.execute_script("window.scrollBy(0, 220);")
      time.sleep(2)

      # Điền từng câu ở trang 2
      print(f"Đang ở trang 2")
      radiogroups = self.driver.find_elements(By.XPATH, "//div[@role='radiogroup']")
      print(f"Tổng số nhóm tìm thấy: {len(radiogroups)}")

      for i, group in enumerate(radiogroups):
          try:
              # Lấy tất cả radio trong nhóm
              radios = group.find_elements(By.XPATH, ".//div[@role='radio']")
              if radios:
                # Chọn ngẫu nhiên hoặc chọn số 5
                choice = random.randint(0, len(radios)-1)
                
                # Điều kiện các cột tuổi và thu nhập
                
                if i == 0:
                  pos_choice = [0,1]
                  choice = random.choice(pos_choice)
                elif i == 3:
                  pos_choice = [0,1,2,3]
                  choice = random.choice(pos_choice)
                # elif i == 2:
                #   choice = 3
                radio = radios[choice]

                # Cuộn đến phần tử đó
                self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", radio)
                time.sleep(0.3)  

                

                # Dùng JavaScript để click mạnh
                self.driver.execute_script("arguments[0].click();", radio)
                print(f"✅ Đã chọn ô thứ {choice+1} cho nhóm {i+1}")
                time.sleep(0.3)
              else:
                  print(f"⚠️ Không tìm thấy radio trong nhóm {i+1}")
          except Exception as e:
              print(f"❌ Lỗi tại nhóm {i+1}: {e}")

      print("🌟 Hoàn tất chọn tất cả radio thành công!")
      time.sleep(3)
      # 13 | click | css=.qs41qe > .l4V7wb | 
      # self.driver.find_element(By.CSS_SELECTOR, ".YhQJj > .l4V7wb").click()
      button = self.driver.find_element(By.XPATH, "//span[text()='Tiếp']")
      self.driver.execute_script("arguments[0].click();", button)
      time.sleep(3)

      # Điền từng câu ở trang 3
      # 14 | click | css=.qs41qe > .vd3tt | Câu 1 mục 1
      # Lấy toàn bộ nhóm radio
      print(f"Đang ở trang 3")
      radiogroups = self.driver.find_elements(By.XPATH, "//div[@role='radiogroup']")
      print(f"Tổng số nhóm tìm thấy: {len(radiogroups)}")

      for i, group in enumerate(radiogroups):
          try:
              # Lấy tất cả radio trong nhóm
              radios = group.find_elements(By.XPATH, ".//div[@role='radio']")
              if radios:
                  # Chọn ngẫu nhiên hoặc chọn số 5
                  choice = random.randint(2, len(radios)-1)
                  radio = radios[choice]

                  # Cuộn đến phần tử đó
                  self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", radio)
                  time.sleep(0.3)

                  # Dùng JavaScript để click mạnh
                  self.driver.execute_script("arguments[0].click();", radio)
                  print(f"✅ Đã chọn ô thứ {choice+1} cho nhóm {i+1}")
                  time.sleep(0.3)
              else:
                  print(f"⚠️ Không tìm thấy radio trong nhóm {i+1}")
          except Exception as e:
              print(f"❌ Lỗi tại nhóm {i+1}: {e}")

      print("🌟 Hoàn tất chọn tất cả radio thành công!")
      time.sleep(3)

      # self.driver.execute_script("window.scrollBy(0, 220);")
      
      self.driver.find_element(By.XPATH, "//span[text()='Tiếp']").click()
      time.sleep(2)

      # 49 | click | css=.qs41qe > .l4V7wb | 
      # self.driver.find_element(By.CSS_SELECTOR, ".qs41qe > .l4V7wb").click()
      # 50 | click | css=.Y5sE8d > .l4V7wb | 
      button = self.driver.find_element(By.XPATH, "//span[text()='Gửi']")
      self.driver.execute_script("arguments[0].click();", button)
      print(f"Đã hoàn thành")
      time.sleep(2)

      # self.teardown_method()

      
  
